<?php

/**
 * AgoraPress sample configuration.
 *
 * Copy this file to `ap-config.php` and fill in values for your environment.
 * The real `ap-config.php` is generated by the installer (or created manually)
 * and must never be committed — it is gitignored.
 *
 * Docker Compose defaults (see docker-compose.yml):
 *   AP_DB_HOST     = db          (service name inside the stack)
 *   AP_DB_NAME     = agorapress
 *   AP_DB_USER     = agorapress
 *   AP_DB_PASSWORD = agorapress
 *   From the host machine, MySQL is published at 127.0.0.1:3307 by default.
 *
 * Supported database drivers (SPEC):
 *   mysql  — MySQL 8.0+ / MariaDB 10.6+ (primary)
 *   sqlite — SQLite 3.35+ (zero-config; path in AP_DB_NAME)
 *   pgsql  — PostgreSQL
 *
 * @package AgoraPress
 */

declare(strict_types=1);

// =============================================================================
// Database settings
// =============================================================================

/**
 * Database driver: 'mysql', 'sqlite', or 'pgsql'.
 */
define('AP_DB_DRIVER', 'mysql');

/**
 * Database name. For SQLite, set this to an absolute path to the .sqlite file
 * (e.g. __DIR__ . '/ap-content/database.sqlite').
 */
define('AP_DB_NAME', 'database_name_here');

/** Database username (ignored for SQLite). */
define('AP_DB_USER', 'username_here');

/** Database password (ignored for SQLite). */
define('AP_DB_PASSWORD', 'password_here');

/**
 * Database host. Use 'localhost' or '127.0.0.1' for local MySQL/MariaDB;
 * use 'db' when running inside the Docker Compose web service.
 * May include a non-default port: '127.0.0.1:3307'.
 */
define('AP_DB_HOST', 'localhost');

/** Connection charset (MySQL/MariaDB). SPEC default: utf8mb4. */
define('AP_DB_CHARSET', 'utf8mb4');

/** Connection collation (MySQL/MariaDB). SPEC default: utf8mb4_unicode_ci. */
define('AP_DB_COLLATE', 'utf8mb4_unicode_ci');

/**
 * Database table prefix. Change only before installation.
 * Default and recommended value: ap_
 *
 * @var string
 */
$table_prefix = 'ap_';

// =============================================================================
// Authentication keys and salts
// =============================================================================
// Generate unique values for each site (installer fills these automatically).
// Changing them after install will invalidate cookies and nonces.

define('AP_AUTH_KEY', 'put your unique phrase here');
define('AP_SECURE_AUTH_KEY', 'put your unique phrase here');
define('AP_LOGGED_IN_KEY', 'put your unique phrase here');
define('AP_NONCE_KEY', 'put your unique phrase here');
define('AP_AUTH_SALT', 'put your unique phrase here');
define('AP_SECURE_AUTH_SALT', 'put your unique phrase here');
define('AP_LOGGED_IN_SALT', 'put your unique phrase here');
define('AP_NONCE_SALT', 'put your unique phrase here');

// =============================================================================
// Debugging (leave off on production)
// =============================================================================

/**
 * Enable debug mode (extra logging / notices). Never leave true on production.
 */
define('AP_DEBUG', false);

/** When true and AP_DEBUG is true, print errors to the browser. */
define('AP_DEBUG_DISPLAY', false);

/** When true and AP_DEBUG is true, write errors to a log file under ap-content. */
define('AP_DEBUG_LOG', false);

/**
 * When true, AP_DB records each SQL statement + timing in getQueries()
 * (performance debugging). Leave false in production — adds memory overhead.
 */
define('AP_SAVEQUERIES', false);

/**
 * When true with AP_DEBUG, also enables query logging (same as AP_SAVEQUERIES).
 */
define('AP_DEBUG_QUERIES', false);

// =============================================================================
// Privacy & optional paths
// =============================================================================

// Privacy: AgoraPress has no telemetry constant, flag, or option. Core never
// phones home with site-identifying data. Hall of Fame is voluntary domain
// registration only (Settings → Hall of Fame).

/**
 * Full-page cache support. When true, AgoraPress loads
 * `ap-content/advanced-cache.php` early (if present) so a page-cache drop-in
 * or reverse-proxy helper can serve/store HTML. Core provides purge hooks
 * (`ap_clean_page_cache`, `ap_clean_post_cache`, …) — it does not ship a
 * disk page-cache engine. Leave false unless you install a compatible drop-in.
 */
define('AP_CACHE', false);

/**
 * Optional absolute path overrides. Leave undefined to use defaults next to
 * this file (AP_ABSPATH . 'ap-content/', AP_ABSPATH . 'ap-content/uploads/').
 *
 * define('AP_CONTENT_DIR', __DIR__ . '/ap-content');
 * define('AP_CONTENT_URL', 'https://example.com/ap-content');
 */

// =============================================================================
// Absolute path — do not edit below this line
// =============================================================================

if (!defined('AP_ABSPATH')) {
    define('AP_ABSPATH', __DIR__ . '/');
}
